# Generated by Django 3.2.7 on 2022-05-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220524_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=255, null=True, verbose_name='цвет'),
        ),
    ]
