# Generated by Django 3.2.7 on 2022-05-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20220524_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='top_sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(null=True, related_name='product_image', to='store.Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='substance',
            field=models.CharField(max_length=25, null=True, verbose_name='Состав ткани'),
        ),
    ]
