# Generated by Django 3.2.7 on 2022-05-24 12:11

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20220524_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
