# Generated by Django 3.2.7 on 2022-05-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_aboutus_aboutusimage_help_news_publicoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
