# Generated by Django 3.2.7 on 2022-05-27 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20220526_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='image',
        ),
        migrations.CreateModel(
            name='HelpImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('help_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.help')),
            ],
        ),
    ]
