# Generated by Django 3.2.7 on 2022-05-27 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20220527_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpimage',
            name='help_obj',
        ),
        migrations.AddField(
            model_name='help',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.helpimage'),
        ),
    ]
