# Generated by Django 3.2.7 on 2022-05-27 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20220527_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='image',
        ),
        migrations.AddField(
            model_name='helpimage',
            name='help_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.help'),
        ),
    ]
