# Generated by Django 3.2.7 on 2022-05-27 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20220527_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpimage',
            name='help_obj',
        ),
    ]
