# Generated by Django 3.2.7 on 2022-05-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_help_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='help',
            options={},
        ),
        migrations.AlterModelOptions(
            name='helpimage',
            options={'verbose_name': 'Вопросы и ответы', 'verbose_name_plural': 'Вопросы и ответы'},
        ),
        migrations.AddField(
            model_name='slider',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
