# Generated by Django 3.2.7 on 2022-05-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_callback'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='callback_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
