# Generated by Django 3.2.7 on 2022-06-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_callback_callback_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='')),
                ('text', models.TextField()),
                ('number', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Первая вкладка',
                'verbose_name_plural': 'Первая вкладка',
            },
        ),
        migrations.CreateModel(
            name='SecondFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('phone', 'номер'), ('почта', 'mail'), ('инстаграм', 'instagram'), ('телеграм', 'telegram'), ('whatsapp', 'whatsapp')], max_length=100)),
                ('link', models.CharField(max_length=100, null=True, verbose_name='ссылка или номер')),
            ],
        ),
    ]
