# Generated by Django 3.2.7 on 2022-06-01 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_firstfooter_secondfooter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secondfooter',
            options={'verbose_name': 'Вторая вкладка', 'verbose_name_plural': 'Вторая вкладка'},
        ),
    ]
