# Generated by Django 3.2.7 on 2022-06-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_client_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Оформлен', 'Оформлен'), ('Отменен', 'Отменен')], max_length=20, null=True),
        ),
    ]
