# Generated by Django 3.2.7 on 2022-06-02 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_auto_20220602_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='product_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.image'),
        ),
    ]
