# Generated by Django 3.2.7 on 2022-06-02 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_orderdetail_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='total_price',
        ),
    ]
