# Generated by Django 3.2.7 on 2022-06-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_auto_20220602_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='product',
            new_name='product_image',
        ),
    ]
