# Generated by Django 3.2.7 on 2022-06-02 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиенты', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='количество в линейке'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=100, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(max_length=100, verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='дата оформления'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='эл. почта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Оформлен', 'Оформлен'), ('Отменен', 'Отменен')], default='Новый', max_length=20, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='client',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_price',
            field=models.IntegerField(null=True, verbose_name='итого к оплате'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_sum',
            field=models.IntegerField(null=True, verbose_name='скидка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_quantity',
            field=models.IntegerField(null=True, verbose_name='количество линеек'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(null=True, verbose_name='стоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_quantity',
            field=models.IntegerField(null=True, verbose_name='количество товаров'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='store.order', verbose_name='заказ'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='store.product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.image', verbose_name='картина/цвет товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(max_length=100, null=True, verbose_name='артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.IntegerField(null=True, verbose_name='скидка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(max_length=100, null=True, verbose_name='материал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=True, verbose_name='новинки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=10, null=True, verbose_name='размер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='top_sales',
            field=models.BooleanField(default=False, verbose_name='хит продаж'),
        ),
    ]
