# Generated by Django 3.2.7 on 2022-06-02 11:16

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_auto_20220602_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='active',
            field=models.BooleanField(default=True, verbose_name='показывать на сайте?'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='icon',
            field=models.ImageField(upload_to='', verbose_name='иконка'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='text',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='title',
            field=models.CharField(max_length=100, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='callback_type',
            field=models.CharField(max_length=100, null=True, verbose_name='тип обращения'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='contacted',
            field=models.BooleanField(default=False, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='name',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='phone_number',
            field=models.CharField(max_length=100, verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(default=None, upload_to='', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='firstfooter',
            name='logo',
            field=models.ImageField(upload_to='', verbose_name='логотип'),
        ),
        migrations.AlterField(
            model_name='firstfooter',
            name='number',
            field=models.CharField(max_length=25, verbose_name='номер в хедере'),
        ),
        migrations.AlterField(
            model_name='firstfooter',
            name='text',
            field=models.TextField(verbose_name='текстовая информация'),
        ),
        migrations.AlterField(
            model_name='help',
            name='answer',
            field=models.TextField(verbose_name='ответ'),
        ),
        migrations.AlterField(
            model_name='help',
            name='question',
            field=models.TextField(verbose_name='вопрос'),
        ),
        migrations.AlterField(
            model_name='helpimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='картина'),
        ),
        migrations.AlterField(
            model_name='image',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='цвет продукта'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='картина под цвет продукта'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='publicoffer',
            name='title',
            field=models.CharField(max_length=100, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='secondfooter',
            name='type',
            field=models.CharField(choices=[('phone', 'номер'), ('почта', 'mail'), ('инстаграм', 'instagram'), ('телеграм', 'telegram'), ('whatsapp', 'whatsapp')], max_length=100, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='active',
            field=models.BooleanField(default=True, verbose_name='показывать на сайте?'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='link',
            field=models.CharField(max_length=150, null=True, verbose_name='ссылка'),
        ),
    ]
