# Generated by Django 3.2.7 on 2022-06-03 04:58

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_auto_20220603_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='количество заказанных товаров'),
        ),
    ]
