# Generated by Django 3.2.7 on 2022-06-03 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_auto_20220603_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondfooter',
            name='footer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.firstfooter'),
        ),
    ]
