# Generated by Django 3.2.7 on 2022-06-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_secondfooter_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutusimage',
            name='about_us',
        ),
        migrations.DeleteModel(
            name='Advantage',
        ),
        migrations.DeleteModel(
            name='CallBack',
        ),
        migrations.RemoveField(
            model_name='help',
            name='image',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='PublicOffer',
        ),
        migrations.RemoveField(
            model_name='secondfooter',
            name='footer',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(help_text='писать в формате: 40-60', max_length=10, null=True, verbose_name='размер'),
        ),
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='AboutUsImage',
        ),
        migrations.DeleteModel(
            name='FirstFooter',
        ),
        migrations.DeleteModel(
            name='Help',
        ),
        migrations.DeleteModel(
            name='HelpImage',
        ),
        migrations.DeleteModel(
            name='SecondFooter',
        ),
    ]
