# Generated by Django 3.2.7 on 2022-06-09 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_auto_20220608_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.client'),
        ),
    ]
