# Generated by Django 3.2.7 on 2022-06-07 04:43

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='', verbose_name='иконка')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('text', models.TextField(verbose_name='описание')),
                ('active', models.BooleanField(default=True, verbose_name='показывать на сайте?')),
            ],
            options={
                'verbose_name': 'Наши преимущества',
                'verbose_name_plural': 'Наши преимущества',
            },
        ),
        migrations.CreateModel(
            name='CallBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('phone_number', models.CharField(max_length=100, verbose_name='номер')),
                ('date', models.DateField(auto_now_add=True)),
                ('callback_type', models.CharField(max_length=100, null=True, verbose_name='тип обращения')),
                ('contacted', models.BooleanField(default=False, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'Обратный звонок',
                'verbose_name_plural': 'Обратный звонок ',
            },
        ),
        migrations.CreateModel(
            name='FirstFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='', verbose_name='логотип')),
                ('text', models.TextField(verbose_name='текстовая информация')),
                ('number', models.CharField(max_length=25, verbose_name='номер в хедере')),
            ],
            options={
                'verbose_name': 'Футер',
                'verbose_name_plural': 'Футер',
            },
        ),
        migrations.CreateModel(
            name='HelpImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='картина')),
            ],
            options={
                'verbose_name': 'Вопросы и ответы',
                'verbose_name_plural': 'Вопросы и ответы',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('image', models.ImageField(upload_to='', verbose_name='картинка')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='PublicOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Публичный оффер',
                'verbose_name_plural': 'Публичный оффер',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='картинка')),
                ('link', models.CharField(max_length=150, null=True, verbose_name='ссылка')),
                ('active', models.BooleanField(default=True, verbose_name='показывать на сайте?')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдер ',
            },
        ),
        migrations.CreateModel(
            name='SecondFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('phone', 'номер'), ('почта', 'mail'), ('инстаграм', 'instagram'), ('телеграм', 'telegram'), ('whatsapp', 'whatsapp')], max_length=100, verbose_name='тип')),
                ('link', models.CharField(help_text='номер в формате - 0555555555', max_length=100, null=True, verbose_name='ссылка или номер')),
                ('footer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='about_store.firstfooter')),
            ],
            options={
                'verbose_name': 'Номера телефонов',
                'verbose_name_plural': 'Номера телефонов',
            },
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='вопрос')),
                ('answer', models.TextField(verbose_name='ответ')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='about_store.helpimage')),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('about_us', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='about_store.aboutus')),
            ],
        ),
    ]
